# Generated by Django 4.1.5 on 2023-01-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoggis', '0004_yoga_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoga',
            name='how_to_perform',
            field=models.TextField(blank=True),
        ),
    ]
