# Generated by Django 4.1.5 on 2023-01-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoggis', '0005_yoga_how_to_perform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoga',
            name='description',
            field=models.TextField(),
        ),
    ]
