# Generated by Django 4.1.5 on 2023-01-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoggis', '0006_alter_yoga_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoga',
            name='avoid_for_disorder',
            field=models.ManyToManyField(blank=True, to='yoggis.userdisorder'),
        ),
    ]
