# Generated by Django 4.1.5 on 2023-01-12 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yoggis', '0007_alter_yoga_avoid_for_disorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogascore',
            name='yoga',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='yoggis.yoga'),
            preserve_default=False,
        ),
    ]
