# Generated by Django 4.1.5 on 2023-01-28 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yoggis', '0008_yogascore_yoga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogascore',
            name='yoga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yogaOwner', to='yoggis.yoga'),
        ),
        migrations.CreateModel(
            name='SUserDisorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_disorder', models.ManyToManyField(blank=True, to='yoggis.userdisorder')),
            ],
        ),
    ]
