# Generated by Django 4.1.5 on 2023-01-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoggis', '0009_alter_yogascore_yoga'),
        ('yoggis', '0009_alter_yogascore_yoga_suserdisorder'),
    ]

    operations = [
    ]
